
const productInfo=
[
    {
        model:"Aston Martin Valour",
        FuelType:"Hybrid",
        Color:"red",
        Information:"Want to get your hands on this lovely Aston Martin throwback? Too bad, it’s already sold out. The V12-powered, manual-transmission Valour was limited to just 110 examples worldwide, and shortly after its debut earlier in 2023, customers quickly snapped up what the company is calling the last of an era. Those lucky 110 customers that did manage to snag one had to shell out at least $1.5 million to start, with options easily pushing it past $2.0 million.",
        Engine:"2993 to 2998 cc",
        PowerandTorque:"335 to 375 bhp & 520 to 700 Nm",
        DriveTrain :"AWD",
        Price:" $1.5 Million",
    brand:"mercery",
    Category:"Sedan",
      Acceleration:'5.8 to 5.9 seconds',
        Image:'./images/20.jpg'
    }  ,
    {
        model:"McLaren Elva",
        FuelType:"Hybrid",
        Color:"blue",
        Information:"The McLaren Elva is one of the latest additions to the British supercar maker’s storied legacy. Even without a proper windshield (though, no option) or roof to rely on, the Elva produces 804 horsepower and 590 pound-feet of torque from its twin-turbocharged 4.0-liter V8. Originally McLaren announced just 399 units, but later the company dropped that to an even more scarce 249 examples. Either way, most of you will never get your hands on one – the Elva costs $1.7 million.",
        Engine:"2993 to 2998 cc",
        Price: "$1.7 Million",
      PowerandTorque:"335 to 375 bhp & 520 to 700 Nm",
        DriveTrain :"AWD",
        brand:"Honda",
        Category:"Sedan",
        Acceleration:'5.8 to 5.9 seconds',
        Image:'./images/mclaren-elva-windshield.jpg'
    } ,
    {
        model:"Czinger 21C",
        FuelType:"Hybrid",
        Color:"yellow",
        Information:"You might not know the name Czinger yet, but this California-based boutique automaker is responsible for the $1.7 million 21C supercar. With 1,250 horsepower on tap thanks to a 2.9-liter twin-turbocharged V8, the 21C can rocket to 60 miles per hour in 1.9 seconds and a top speed of around 281 miles per hour.",
        Engine:"2993 to 2998 cc",
        PowerandTorque:"335 to 375 bhp & 520 to 700 Nm",
        DriveTrain :"AWD",
        Price:" $1.7 Million",
        brand:"Wagon",
        Acceleration:'5.8 to 5.9 seconds',
        Category:"Coupe",
        Image:'./images/czinger-21c.jpg'
    }  ,
    {
        model:"Ferrari Monza",
        FuelType:"Hybrid",
        Color:"green",
        Engine:"2993 to 2998 cc",
        Information:"ferrari-monza-sp1.jpg",
        PowerandTorque:"335 to 375 bhp & 520 to 700 Nm",
        DriveTrain :"AWD",
        Price:"$1.7 Million",
        brand:"Sedan",
        Acceleration:'5.8 to 5.9 seconds',
        Category:"SUV (Sports Utility Vehicle)",
        Image:'./images/ferrari-monza-sp1.jpg'
    }  , 
    {
        model:"Gordon Murray T.33",
        FuelType:"Hybrid",
        Color:"pink",
        Information:"The second and slightly more affordable supercar in the new Gordon Murray lineup is the T.33. With 607 horsepower courtesy of a naturally aspirated 3.9-liter V12, the T.33 revs to a ridiculous 10,500 RPM. With a price tag of around $1.7 million at current conversion rates, Gordon Murray automotive promises to sell this car globally, in both right- and left-hand-drive configurations. Too bad it's already sold out.",
        Engine:"2993 to 2998 cc",
        PowerandTorque:"335 to 375 bhp & 520 to 700 Nm",
        DriveTrain :"AWD",
        Price:" $1.7 Million",
        Category:"SUV (Sports Utility Vehicle)",
        brand:"Honda",
        Acceleration:'5.8 to 5.9 seconds',
        Image:'./images/koenigsegg-gemera.jpg'
    }  , 
    {
        model:"BmwX7",
        FuelType:"Hybrid",
        Engine:"2993 to 2998 cc",
        PowerandTorque:"335 to 375 bhp & 520 to 700 Nm",
        DriveTrain :"AWD",
        Price:"Rs 100",
        Category:"Crossover",
        brand:"BMW",
        Color:"green",
        Acceleration:'5.8 to 5.9 seconds',
        Image:'./images/bmwx7.jpeg'
    }  , 
    {
        model:"Zenvo TSR-S",
        brand:"suzuki",
        FuelType:"Hybrid",
        Category:"Crossover",
        Engine:"2993 to 2998 cc",
        PowerandTorque:"335 to 375 bhp & 520 to 700 Nm",
        DriveTrain :"AWD",
        Price:" $1.7 Million",
        Color:"red",
       Acceleration:'5.8 to 5.9 seconds',
        Image:'./images/mazzanti-evantra-millecavalli.jpg'
    } ] 
    // 50 car added
const secondProduct= [{ "brand": "Toyota", "model": "Camry", "engine": "2.5L 4-cylinder", Category:"Sedan",   Color:"blue",},
        { "brand": "Honda", "model": "Civic", "engine": "1.5L 4-cylinder","Image" :"./images/front-left-side-47.webp", Category:"Sedan",  Color:"yellow",},
        { "brand": "Ford", "model": "Mustang", "engine": "5.0L V8" ,"Image" :"./images/2018_Ford_Mustang_GT_5.0.jpg",Category:" Convertible" , Color:"yellow",},
        { "brand": "Chevrolet", "model": "Malibu", "engine": "1.5L 4-cylinder","Image" :"./images/2018_Ford_Mustang_GT_5.0.jpg" ,Category:" Convertible",Color:"yellow"},
        { "brand": "Volkswagen", "model": "Jetta", "engine": "1.4L 4-cylinder","Image" :"./images/2018_Ford_Mustang_GT_5.0.jpg" ,Category:" Convertible",Color:"red"},
        { "brand": "Nissan", "model": "Altima", "engine": "2.5L 4-cylinder","Image" :"./images/2018_Ford_Mustang_GT_5.0.jpg" ,Category:" Convertible",Color:"green"},
        { "brand": "Hyundai", "model": "Elantra", "engine": "2.0L 4-cylinder","Image" :"./images/2018_Ford_Mustang_GT_5.0.jpg",Category:" Convertible",Color:"green" },
        { "brand": "BMW", "model": "3 Series", "engine": "2.0L 4-cylinder","Image" :"./images/2018_Ford_Mustang_GT_5.0.jpg",Category:"Sedan",Color:"yellow"},
        { "brand": "Mercedes-Benz", "model": "C-Class", "engine": "2.0L 4-cylinder" },
        { "brand": "Audi", "model": "A4", "engine": "2.0L 4-cylinder","Image" :"./images/2018_Ford_Mustang_GT_5.0.jpg",Category:"Sedan",Color:"yellow" },
        { "brand": "Lexus", "model": "ES", "engine": "3.5L V6","image" :"./images/2018_Ford_Mustang_GT_5.0.jpg" ,Category:"Sedan",Color:"red"},
        { "brand": "Subaru", "model": "Impreza", "engine": "2.0L 4-cylinder" ,"Image" :"./images/2018_Ford_Mustang_GT_5.0.jpg", Category:"Coupe", Color:"green"},
        { "brand": "Mazda", "model": "Mazda3", "engine": "2.5L 4-cylinder" ,"Image" :"./images/2018_Ford_Mustang_GT_5.0.jpg",Category:"Coupe",Color:"yellow"},
        { "brand": "Kia", "model": "Optima", "engine": "2.4L 4-cylinder","Image" :"./images/2018_Ford_Mustang_GT_5.0.jpg",Category:"Coupe" ,Color:"blue"},
        { "brand": "Tesla", "model": "Model 3", "engine": "Electric" ,"Image" :"./images/2018_Ford_Mustang_GT_5.0.jpg",Category:"Coupe",Color:"blue"},
        { "brand": "Chevrolet", "model": "Camaro", "engine": "6.2L V8",Category:"Hatchback",Color:"green" },
        { "brand": "Ford", "model": "Fusion", "engine": "2.5L 4-cylinder",Category:"Hatchback",Color:"green" },
        { "brand": "Toyota", "model": "Corolla", "engine": "1.8L 4-cylinder",Category:"Hatchback",Color:"red" },
        { "brand": "Honda", "model": "Accord", "engine": "1.5L 4-cylinder",Category:"Hatchback",Color:"red" },
        { "brand": "Volkswagen", "model": "Passat", "engine": "2.0L 4-cylinder",Category:"Hatchback",Color:"green"},
        { "brand": "Nissan", "model": "Maxima", "engine": "3.5L V6" },
        { "brand": "Hyundai", "model": "Sonata", "engine": "2.5L 4-cylinder",Category:"Coupe" ,Color:"black"},
        { "brand": "BMW", "model": "5 Series", "engine": "2.0L 4-cylinder",Category:"Coupe",Color:"black" },
        { "brand": "Mercedes-Benz", "model": "E-Class", "engine": "2.0L 4-cylinder",Category:"Coupe" ,Color:"green"},
        { "brand": "Audi", "model": "A6", "engine": "2.0L 4-cylinder",Category:"Coupe",Color:"blue" },
        { "brand": "Lexus", "model": "IS", "engine": "2.0L 4-cylinder",Category:"Coupe",Color:"blue" },
        { "brand": "Subaru", "model": "Legacy", "engine": "2.5L 4-cylinder",Category:"Crossover",Color:"gray"  },
        { "brand": "Mazda", "model": "Mazda6", "engine": "2.5L 4-cylinder",Category:"Crossover",Color:"gray" },
        { "brand": "Kia", "model": "Stinger", "engine": "2.0L 4-cylinder",Category:"Crossover",Color:"blue" },
        { "brand": "Tesla", "model": "Model S", "engine": "Electric",Category:"Crossover",Color:"blue" },
        { "brand": "Chevrolet", "model": "Impala", "engine": "3.6L V6",Category:"Crossover",Color:"red"},
        { "brand": "Chevrolet", "model": "Impala", "engine": "3.6L V6",Category:"Crossover",Color:"red" },
        { "brand": "Ford", "model": "Taurus", "engine": "3.5L V6" ,Category:"Wagon",color:"red"},
        { "brand": "Toyota", "model": "Avalon", "engine": "3.5L V6",Category:"Wagon" ,Color:"blue" },
        { "brand": "Honda", "model": "Insight", "engine": "1.5L 4-cylinder",Category:"Wagon",Color:"blue"  },
        { "brand": "Volkswagen", "model": "Arteon", "engine": "2.0L 4-cylinder",Category:"Wagon",Color:"green"  },
        { "brand": "Nissan", "model": "Sentra", "engine": "2.0L 4-cylinder",Category:"Wagon",Color:"blue" },
        { "brand": "Hyundai", "model": "Veloster", "engine": "2.0L 4-cylinder",Category:"Wagon",Color:"white"  },
        { "brand": "BMW", "model": "7 Series", "engine": "3.0L 6-cylinder",Category:"SUV (Sports Utility Vehicle)",Color:"blue"  },
        { "brand": "Mercedes-Benz", "model": "S-Class", "engine": "3.0L 6-cylinder",Category:"SUV (Sports Utility Vehicle)",Color:"yellow"  },
        { "brand": "Audi", "model": "A8", "engine": "3.0L 6-cylinder" ,Category:"SUV (Sports Utility Vehicle)",Color:"blue"},
        { "brand": "Lexus", "model": "LS", "engine": "3.5L V6" },
        { "brand": "Subaru", "model": "WRX", "engine": "2.0L 4-cylinder",Category:"SUV (Sports Utility Vehicle)",Color:"black" },
        { "brand": "Mazda", "model": "MX-5 Miata", "engine": "2.0L 4-cylinder",Category:"SUV (Sports Utility Vehicle)",Color:"black" },
        { "brand": "Kia", "model": "Soul", "engine": "2.0L 4-cylinder" ,Category:"SUV (Sports Utility Vehicle)",Color:"black"},
        { "brand": "Tesla", "model": "Model X", "engine": "Electric",Category:"SUV (Sports Utility Vehicle)" ,Color:"green"},
        { "brand": "Chevrolet", "model": "Equinox", "engine": "1.5L 4-cylinder",Category:"SUV (Sports Utility Vehicle)",Color:"yellow" },
        { "brand": "Ford", "model": "Escape", "engine": "1.5L 4-cylinder",Color:"yellow" },
        { "brand": "Toyota", "model": "Rav4", "engine": "2.5L 4-cylinder",Color:"yellow" },
        { "brand": "Honda", "model": "CR-V", "engine": "1.5L 4-cylinder",Color:"yellow"}];

secondProduct.forEach((value)=>{
    productInfo.push(value)
})

export {productInfo};
